name: Linux Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup Env
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
    - name: Install dependencies
      shell: bash
      run: |
          sudo apt install -y verilator libgmp-dev libmpfr-dev libmpc-dev
    - name: Install Python packages
      shell: bash -l {0}
      run: |
          cd onyx
          pip install pytest pytest-pycodestyle
          pip install -e .
    - name: Pytest
      shell: bash -l {0}
      run: |
        pytest --pycodestyle tests/ onyx_sram_subsystem/
